Release 0.8
dusk-network/nstack pull request #27
Opened 2021-04-21 17:02 UTC by krl

2021-04-21 17:04 UTC, krl commented
fixes #24, #26

2021-04-26 17:36 UTC, ZER0 requested changes
Few things to fix before merging into the default branch.

A couple of things not mentioned in the comments:

1.  Add a proper description for the PR (you can basically copy the changelog in the description, plus adding "Resolves: xx" where xx is the issue is resolving.
2. Run clippy and ensure is not emit any warnings (either allowing something or fixing something. If you allow something a comment about why should be added)

2021-04-26 17:36 UTC, ZER0 commented on documentation/announcement.md
> +# Announcing nstack 0.8
You can safely delete the whole `documentation` folder (see the wiki)

2021-04-27 09:50 UTC, ZER0 approved these changes
LGTM!

2021-04-27 10:02 UTC, merged